### ISSUE TITLE
mapLink 'Click Here' should open in a new tab

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/cbrs-mapper-v2#1]
`$("#mapLink").html('<a href=' + attr["Map_Link"] + 'target="_blank">Click Here</a>');` 

This doesn't work. It's adding "target="_blank" to the end of the url. I've removed it for now so it's just opening in the same tab.

**Comment by njestes** [comment]
I think you need to add a couple double quotes and a space in there in there.

This should work:

```$("#mapLink").html('<a href=*"*' + attr["Map_Link"] + ' *"*target="_blank">Click Here</a>');```

**Comment by lprivette** [comment]
yep, that fixed it. thanks!
