### ISSUE TITLE
Replace Measure Tools from flex application?

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/cbrs-mapper-v2#13]
Flex CBRS Mapper has measure tools (see screenshot):

![image](https://cloud.githubusercontent.com/assets/12058013/24415843/d03cfdca-13b0-11e7-92a6-b665c430c4e3.png)

**Comment by HansVraga** [comment]
@njestes Do you know if these need to be brought forward into v2?

**Comment by lprivette** [comment]
it's just measuring area and distance right? I think it's exactly what's in the v2 map already.

**Comment by njestes** [comment]
Yeah, that's all that's needed @lprivette @HansVraga 

Already there because you worked off of the wetlands v2 mapper
