### ISSUE TITLE
Legend cleanup

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/cbrs-mapper-v2#14]
Two items related to aligning the Legend more closely to the flex application:

- [ ] redundant heading in Legend

- [ ] Link to Unit definitions

Flex Legend:
![image](https://cloud.githubusercontent.com/assets/12058013/24415978/37fb0f2e-13b1-11e7-8cfd-2f174a53898e.png)

Note the link that will open up the Unit Definitions (which we've parked in About). We should offer the same capability.

JS Legend:
![image](https://cloud.githubusercontent.com/assets/12058013/24416069/7d050048-13b1-11e7-97f9-4d2cb7469009.png)

The titles are redundant, can we reduce them to match the flex Legend titles?

**Comment by lprivette** [comment]
I'm kind of unsure at how to fix this. Any suggestions @njestes ? I tried making the `.esriLegendLayerLabel` and `.esriLegendServiceLabel` hidden. Having the `.esriLegend
![image](https://cloud.githubusercontent.com/assets/23640741/24456579/6fe2676a-1461-11e7-95da-1d207d2d3bc2.png)

both titles have the `.esriLegendLayerLabel` so then both are then hidden and there is a big white space :-/

Maybe I can display them custom using the `renderer.addValue` method?
