### ISSUE TITLE
Remove Data Accuracy tier from pop-up

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/cbrs-mapper-v2#27]
From Cooperator:
>We are discontinuing the data accuracy tier because all units have been digitally converted and are tier 2 so there is no need to draw this distinction.  Remove this attribute from the identify results.

![image](https://cloud.githubusercontent.com/assets/12058013/25006922/b70252b4-202c-11e7-9f67-579a916de8b0.png)

**Comment by lprivette** [comment]
Is this dependent on using the new, updated database that Paul has?
