### ISSUE TITLE
Enable Backups of prod CBRS-mapper-v2

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/cbrs-mapper-v2#33]
Going through the go-live checklist here: https://docs.google.com/document/d/1afB0bih4lv2BvflQK_hySFOGWR8o8fSRRtqYG5_hm7g/edit

I'm not sure if backups are something that is down within AWS or not. If not, what do I need to do?

**Comment by aaronstephenson** [comment]
This is a purely JavaScript app, right? And you have it in GitHub? Then there's nothing more to do. I'm pretty sure @hans meant that checklist item only for serverside apps.

**Comment by HansVraga** [comment]
Thanks for the benefit of the doubt @aaronstephenson but I actually thought to myself "I wonder if FWS S3 (where I figured it would live, not the server) has versioning on" - of course, the code is in the repo which we rely on GitHub to back up. The services (I presume) are being hosted by the FWS ArcServer which (I presume) has the same backup polices as the rest of our systems - so every aspect of this system is covered for backups - I think this can be closed.
