### ISSUE TITLE
Stand up new ArcEnterprise system for CBRS layers/products

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/cbrs-mapper-v2#46]
Initial need is to host the map layers behind the CBRS Projects Mapper and CBRS Mapper.

Near future (October) this will be serving out a CBRS layer to a FEMA product (NFHL map) that FEMA says: NFHL map service currently experiences 30 million hits per month and increasing.

Near future (end of this FY, if possible) there is also the desire for a handful of CBRS personnel (estimate 4) to have the ability to publish services to this server. Question related to this that we should consider as part of this task - Will we need a jump server?  Perhaps we also stand up a small a test server for standing up test services which they could publish to Prod server from?

**Comment by aaronstephenson** [comment]
A few questions:
1. How many services (and how many layers) will be hosted?
2. Will they be map services or feature or something else?
3. If map services, can they be cached?
4. How much data will these services serve (count and complexity of objects within the services)?
5. What will be used for data storage?
6. Will there be significant file storage?
7. Will users be able to edit data or upload files?
... and probably more

**Comment by HansVraga** [comment]
@lprivette can you take a pass on answers for these based on the current applications?

**Comment by HansVraga** [comment]
(maybe with @kjacobsen16 while you show her the existing stuff?)

**Comment by lprivette** [comment]
**1. How many services (and how many layers) will be hosted?**

> Subject to change, but it will likely have these layers that are currently hosted on FWS Primary https://fwsprimary.wim.usgs.gov/server/rest/services/CBRAMapper/GeoCBRA/MapServer  + 2 new layers (FEMA layer and possibly CBRS Community layer)
> 
> So estimating 1 map server with 7 services?

**2. Will they be map services or feature or something else?**

> They would be Map Services that contain Feature Layers that we'll set up to support dynamic layers

**3. If map services, can they be cached?**

> I don't know the answer to this one. How would I determine whether or not they should be cached? These layers aren't huge. 

**4. How much data will these services serve (count and complexity of objects within the services)?**

> current mapper's data is 59 MB. New layer is 5 MB. We don't know about the CBRA Community layer and Paul's not sure that one will even happen. So I think it will definitely be less than 1 GB. All layers consist of polygons.

**5. What will be used for data storage?**

> Sorry, but I don't understand this question. The client would be in s3 if that helps.

**6. Will there be significant file storage?**

> No

**7. Will users be able to edit data or upload files?**

> No

**Comment by aaronstephenson** [comment]
Thanks Lauren, that helps. Let's chat IRL to clear some things up, but for question 5 what I want to know is where the data used by the map services will be stored... files, file geodatabases, RDBMS, something else?

**Comment by aaronstephenson** [comment]
@lprivette how soon is this needed?

**Comment by lprivette** [comment]
Sometime this month if possible.

**Comment by lprivette** [comment]
Actually, would it be possible to have this setup sooner? @aaronstephenson 

We've been causing issues by deploying new services/data on the FWS-Primary prod server.

**Comment by HansVraga** [comment]
Misclick on the close, above.

**Comment by HansVraga** [comment]
Closing in favor of https://github.com/USGS-WiM/cbrs-mapper-v2/issues/56
