### ISSUE TITLE
CBRS Cloud Infrastructure Tasks

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/cbrs-mapper-v2#56]
- [x] Request new managed ArcServer instance for serving Production Map Services
- [x] Request new managed ArcServer instance for serving Test Map Services
- [x] Launch new Jump server for publishing map services to Test & Prod ArcServers
- [x] Set up local accounts for Jump Server
- [x] Set up AGS publisher accounts for publishing from Jump Server
- [x] Set up AWS IAM accounts with specific, limited permissions for CLI (to start/stop Test ArcServer)

**Comment by aaronstephenson** [comment]
EC2 instances created by the vendor last week. Will work with @DanielJBeckman to finish their setup.

**Comment by aaronstephenson** [comment]
AGS Prod is ready to go: https://cbrsgis.wim.usgs.gov/arcgis

Dan will now begin setting up AGS Test, should be ready shortly: https://cbrsgistest.wim.usgs.gov/arcgis

**Comment by DanielJBeckman** [comment]
I think this one is done.

**Comment by HansVraga** [comment]
@kjacobsen16 - can you confirm this is ready to go?

**Comment by kjacobsen16** [comment]
Yes, this issue is done. Thanks Dan!
