### ISSUE TITLE
IE issues with the Validation tool

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/cbrs-mapper-v2#59]
![image](https://user-images.githubusercontent.com/12058013/46150209-0efaa880-c23a-11e8-888e-5ce7f7851a8f.png)

**Comment by kjacobsen16** [comment]
![image](https://user-images.githubusercontent.com/35497731/46150540-68f77000-c232-11e8-8019-8e180b62ef41.png)

**Comment by HansVraga** [comment]
couldnt do the certify step

**Comment by kjacobsen16** [comment]
fixed, woo
