### ISSUE TITLE
Utility using FWS Primary continuing to have issues

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/cbrs-mapper-v2#69]
We use a utility [here](https://fwsprimary.wim.usgs.gov/server/rest/services/Utilities/PrintingTools/GPServer/Export%20Web%20Map%20Task/) that runs from FWS Primary to create a .pdf.

The utility slows down for minutes at a time, making the tool unusable part of the time. The timeout is set at 90 seconds, when the tool is running normally it takes ~4 seconds. I've tried running the tool through our application [here](https://test.wim.usgs.gov/cbrsv2/) using the "CBRS Validation Tool" in the nav bar, as well as executing directly from the utility.

The C: drive on FWS Primary was almost full, and clearing it out appeared to fix the issue. However, since I'm seeing the same issues today I'm thinking that was coincidental.

FWS Primary also flickered out for a few minutes yesterday.

**Comment by aaronstephenson** [comment]
You might need to increase the maximum number of "instances" available to this service in the ArcGIS Service Properties. The default is 2, but that's not sufficient for a production service.
![image](https://user-images.githubusercontent.com/8713712/52147508-8c8d5580-262c-11e9-8b7b-749195c2826d.png)

**Comment by aaronstephenson** [comment]
Are you still using the utility from FWS Primary, or have you transitioned to the CBRS server?

**Comment by kjacobsen16** [comment]
I've transitioned it to the CBRS server, but I'm getting timeouts again.

I'll double-check things on my end and make sure there wasn't some change I forgot about.

It's possible it's slowing down due to the custom template elements, but again it's strange that this wasn't happening a couple months ago.

**Comment by kjacobsen16** [comment]
fixed - the issue was caused when the CBRS team stopped reprojecting their data. Preserving the map's scale rather than the map extent in the printout fixed the issue
