### ISSUE TITLE
Acquire Reserved Instances for CBRS Production EC2s and RDS

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/cbrs-mapper-v2#70]
CBRS systems have been stable and no major changes are planned. Time to save some $$. Let's get reserved tags for the Production EC2 AGS instance and Webserver, as well as the CBRS RDS

**Comment by aaronstephenson** [comment]
Email sent to Zivaro.

**Comment by aaronstephenson** [comment]
Emailed Zivaro again to prompt action.

**Comment by aaronstephenson** [comment]
Confirmed purchased today (Feb 28)
