### ISSUE TITLE
Add CBRS Test Instances to Auto Shutdown

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/cbrs-mapper-v2#71]
These systems are only used a few days here and there. We'll start-up Test Instances on demand, and let the shutdown kill them at the end of the day.

There should be an EC2 AGS Test and a EC2 Webserver Test

**Comment by aaronstephenson** [comment]
Done. I have a lambda function that will shut down the test AGS and test web servers, and also the linux and windows bastion servers, every night. I also have a weekday start up lambda function to turn on the two test servers, but I have left that disabled.
